version: "3.8"

services:
  backend:
    build:
      context: ./backend # Point to the backend directory
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "8000:8000" # Expose the backend API on port 8000
    volumes:
      - ./backend:/app # Mount the backend code for live reloads
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000

  frontend:
    build:
      context: ./frontend # Point to the frontend directory
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "3000:3000" # Expose the frontend on port 3000
    volumes:
      - ./frontend:/app # Mount the frontend code for live reloads
    environment:
      - REACT_APP_API_URL=http://localhost:8000 # Point to the backend API
